### ISSUE TITLE
Separate runner logic from grader

### ISSUE THREAD

**Issue by nmagerko** [illinois-cs241/broadway#13]
Right now there is essentially a single file that has all of the functions needed to start up the grader and run it.

I would suggest we make a `Grader` class that contains any grading logic and that we put it inside of the `grader` module. Then at the top level (outside of the module) we have a `run.py` that instantiates the grader and gets things running.

I think this would make things a bit easier to maintain.

**Comment by ayushr2** [comment]
@rod-lin I think we can close this?

**Comment by ayushr2** [comment]
Yeah I think this has been done by @rod-lin when we made a mono-repo for Broadway
