### ISSUE TITLE
Merge broadway-api and broadway-grader into one repository and tag releases

### ISSUE THREAD

**Issue by rod-lin** [illinois-cs241/broadway#14]
Since broadway-api and broadway-grader share some common parts and most changes usually require changing both repos, putting them in one repo might be more friendly to both maintainers and users.

Also as @ayushr2 mentioned, bundling them together and start tagging releases may help avoid compatibility issues in the future.

**Comment by ayushr2** [comment]
@rod-lin I am closing this as I had updated the contributions and wiki. The readme looks good.
